spring.application.name=mindconnectzoommeeting
spring.datasource.url=jdbc:mysql://localhost:3306/meeting
spring.datasource.username=root
spring.datasource.password=nikhil
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mindconnect8@gmail.com
spring.mail.password=ymcc lyeg wazh wgxe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
